---
output:
  md_document:
    variant: markdown_github
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figure/",
  fig.height = 1
)
```

# Animated Palettes



## Installation

```r
devtools::install_github("Eomesodermin/animated", force = TRUE)
```

## Usage

```{r, palettes_dummy}
library("animated")

# See all palettes
names(animated_palettes)
```

## Palettes

### A_Bugs_life

```{r, A_Bugs_life}
animated("A_Bugs_life")
```


### Aladdin

```{r, Aladdin}
animated("Aladdin")
```


### Finding_Nemo

```{r, Finding_Nemo}
animated("Finding_Nemo")
```

### Inside_out

```{r, Inside_out}
animated("Inside_out")
```

### Lion_King

```{r, Lion_King}
animated("Lion_King")
```

### Monsters_Inc

```{r, Monsters_Inc}
animated("Monsters_Inc")
```

### Ratatouille

```{r, Ratatouille}
animated("Ratatouille")
```

### Up

```{r, Up}
animated("Up")
```


```{r, ggplot1, fig.height = 3}
library("ggplot2")
ggplot(mtcars, aes(factor(cyl), fill=factor(vs))) +  geom_bar() +
  scale_fill_manual(values = animated("A_Bugs_life"))
```

```{r, volcano, fig.height = 3}
pal <- animated("A_Bugs_life", 21, type = "continuous")
image(volcano, col = pal)
```

